# These are supported funding model platforms

github: ['zeinzo', 'riz-ex', 'aryazakaria01', 'FeriEXP']
community_bridge: zeinzo-project
custom: ['https://t.me/zeinproject', 'https://t.me/punyazein']
